version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net-scrt
    volumes:
      - ./data:/app/data


networks:
  net-scrt:
    external: true